export const filieresDetails = {
  "sage-femme": {
    nom: "Sage-Femme",
    couleur: "pink",
    duree: "3 ans",
    niveau: "Baccalauréat",
    diplome: "Diplôme d'État",
    description:
      "Formez-vous à l'accompagnement de la grossesse, de l'accouchement et du suivi postnatal. Une filière centrée sur la santé de la mère, du nouveau-né et de la famille.",
    programme: [
      "Anatomie-Physiologie",
      "Obstétrique & Gynécologie",
      "Pédiatrie & Néonatologie",
      "Consultations prénatales",
      "Soins postnataux",
      "Santé de la reproduction",
    ],
    debouches: [
      "Maternités",
      "Centres de santé",
      "Cabinets libéraux",
      "Services de néonatologie",
    ],
    paiement: [
      { type: "Inscription", niveau: "Licence 1", montant: 180500 },
      {
        type: "Inscription",
        niveau: "Licence 2",
        montant: 138000,
        sans_blouse: 131000,
      },
      {
        type: "Inscription",
        niveau: "Licence 3",
        montant: 178000,
        sans_blouse: 171000,
      },
      { type: "Mensualité", montant: 40000 },
    ],
  },
  infirmier: {
    nom: "Infirmier d'État",
    couleur: "red",
    duree: "3 ans",
    niveau: "Baccalauréat",
    diplome: "Diplôme d'État",
    description:
      "Développez les compétences nécessaires pour assurer les soins, la surveillance clinique, la prise en charge des urgences et l'accompagnement des patients.",
    programme: [
      "Soins infirmiers fondamentaux",
      "Pathologies médicales",
      "Urgences & Réanimation",
      "Pharmacologie",
      "Hygiène hospitalière",
      "Santé communautaire",
    ],
    debouches: [
      "Hôpitaux publics/privés",
      "Blocs opératoires",
      "Services d'urgence",
      "ONG et structures communautaires",
    ],
    paiement: [
      { type: "Inscription", niveau: "Licence 1", montant: 180500 },
      {
        type: "Inscription",
        niveau: "Licence 2",
        montant: 138000,
        sans_blouse: 131000,
      },
      {
        type: "Inscription",
        niveau: "Licence 3",
        montant: 178000,
        sans_blouse: 171000,
      },
      { type: "Mensualité", montant: 40000 },
    ],
  },
  "assistant-infirmier": {
    nom: "Assistant Infirmier d'État",
    couleur: "blue",
    duree: "2 ans",
    niveau: "Niveau 3ème / BFEM",
    diplome: "Diplôme d'État",
    description:
      "Préparez-vous à assister l'équipe soignante dans les soins de base, le suivi des patients, l'hygiène hospitalière et les gestes techniques du quotidien.",
    programme: [
      "Gestes techniques de base",
      "Prise des paramètres vitaux",
      "Pansements simples",
      "Hygiène & Prévention",
      "Secourisme",
      "Relation d'aide",
    ],
    debouches: [
      "Postes de santé",
      "Cliniques",
      "Cabinets médicaux",
      "Assistance à domicile",
    ],
    paiement: [
      { type: "Inscription", montant: 180500, montantReduit: 125000 },
      { type: "Mensualité", montant: 35000 },
    ],
  },
  "aide-soignant": {
    nom: "Aide-Soignant",
    couleur: "orange",
    duree: "2 ans",
    niveau: "BFEM",
    diplome: "Attestation de Fin de Formation",
    description:
      "Apprenez à accompagner les patients dans les gestes essentiels du quotidien : hygiène, confort, mobilité, alimentation et soutien moral.",
    programme: [
      "Soins d'hygiène & confort",
      "Nutrition & Diététique",
      "Manutention des patients",
      "Psychologie du patient",
      "Prévention des infections",
      "Entretien de l'environnement de soins",
    ],
    debouches: [
      "Maisons de retraite",
      "Centres de convalescence",
      "Services hospitaliers",
      "Assistance à domicile",
    ],
    paiement: [
      { type: "Inscription", niveau: "Licence 1", montant: 109500 },
      { type: "Inscription", niveau: "Licence 2", montant: 109500 },
      { type: "Mensualité", montant: 25000 },
    ],
    note: [
      "Pour les étudiants souhaitant obtenir une blouse blanche pour les travaux pratiques (TP), un montant supplémentaire de 10 000 FCFA doit être versé lors de l’inscription.",
    ],
  },
  "delegue-medical": {
    nom: "Délégué Médical",
    couleur: "emerald",
    duree: "10 mois",
    niveau: "BFEM",
    diplome: "Certificat de Qualification Professionnelle",
    description:
      "Maîtrisez la communication médicale, la présentation des produits de santé et la relation professionnelle avec les médecins, pharmaciens et structures sanitaires.",
    programme: [
      "Marketing pharmaceutique",
      "Pharmacologie générale",
      "Techniques de vente",
      "Communication médicale",
      "Anatomie & pathologies",
      "Droit pharmaceutique",
    ],
    debouches: [
      "Laboratoires pharmaceutiques",
      "Agences de promotion médicale",
      "Répartiteurs pharmaceutiques",
      "Structures de distribution de produits de santé",
    ],
    paiement: [
      { type: "Inscription", montant: 100000, montantReduit: 0 },
      { type: "Mensualité", montant: 30000 },
    ],
  },
  "vendeur-pharmacie": {
    nom: "Vendeur(se) en Pharmacie",
    couleur: "violet",
    duree: "10 mois",
    niveau: "BFEM",
    diplome: "Certificat de Qualification Professionnelle",
    description:
      "Formez-vous à l'accueil, au conseil en pharmacie, à la gestion des stocks et à la délivrance des produits de santé sous la responsabilité du pharmacien.",
    programme: [
      "Accueil & conseil client",
      "Médicaments usuels",
      "Gestion des stocks",
      "Logiciels de pharmacie",
      "Parapharmacie",
      "Réglementation des ordonnances",
    ],
    debouches: [
      "Pharmacies",
      "Parapharmacies",
      "Dépôts pharmaceutiques",
      "Grossistes et répartiteurs",
    ],
    paiement: [
      { type: "Inscription", montant: 100000, montantReduit: 0 },
      { type: "Mensualité", montant: 30000 },
    ],
  },
  "secretaire-medical": {
    nom: "Secrétaire Médical(e)",
    couleur: "cyan",
    duree: "10 mois",
    niveau: "BFEM",
    diplome: "Certificat de Qualification Professionnelle",
    description:
      "Apprenez à gérer l'accueil des patients, les rendez-vous, les dossiers médicaux, la terminologie médicale et la confidentialité administrative.",
    programme: [
      "Accueil des patients",
      "Gestion des rendez-vous",
      "Dossiers médicaux",
      "Terminologie médicale",
      "Bureautique médicale",
      "Confidentialité & facturation",
    ],
    debouches: [
      "Cabinets médicaux",
      "Cliniques",
      "Hôpitaux",
      "Laboratoires d'analyses",
      "Centres de santé",
    ],
    paiement: [
      { type: "Inscription", montant: 100000, montantReduit: 0 },
      { type: "Mensualité", montant: 30000 },
    ],
  },
};
